version: "3.9"
services:
  bitcoin_price:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: > 
      sh -c "yarn 
      && yarn dev"
